// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAni3aZDch_ffQo3ywrHiKL9jsHNouI-vA',
    appId: '1:346081394400:web:e40d33202806e0ccfc5a85',
    messagingSenderId: '346081394400',
    projectId: 'vaxtrack-ph',
    authDomain: 'vaxtrack-ph.firebaseapp.com',
    storageBucket: 'vaxtrack-ph.firebasestorage.app',
    measurementId: 'G-N74KCXF0RT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa83PbXH24vYAQpTrLKtBoAZ8E_YdGLxI',
    appId: '1:346081394400:android:268415e5fcba869cfc5a85',
    messagingSenderId: '346081394400',
    projectId: 'vaxtrack-ph',
    storageBucket: 'vaxtrack-ph.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIS9MDB5fGKbYJA4c33_WONAUzquCYY7o',
    appId: '1:346081394400:ios:b9f59e6719427f9dfc5a85',
    messagingSenderId: '346081394400',
    projectId: 'vaxtrack-ph',
    storageBucket: 'vaxtrack-ph.firebasestorage.app',
    iosBundleId: 'com.example.vaxtrackPh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIS9MDB5fGKbYJA4c33_WONAUzquCYY7o',
    appId: '1:346081394400:ios:b9f59e6719427f9dfc5a85',
    messagingSenderId: '346081394400',
    projectId: 'vaxtrack-ph',
    storageBucket: 'vaxtrack-ph.firebasestorage.app',
    iosBundleId: 'com.example.vaxtrackPh',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAni3aZDch_ffQo3ywrHiKL9jsHNouI-vA',
    appId: '1:346081394400:web:f9084042e6a202fbfc5a85',
    messagingSenderId: '346081394400',
    projectId: 'vaxtrack-ph',
    authDomain: 'vaxtrack-ph.firebaseapp.com',
    storageBucket: 'vaxtrack-ph.firebasestorage.app',
    measurementId: 'G-N9KFJHREXX',
  );
}
